### ISSUE TITLE
Release 1.6 can't be compiled if ncc is not installed

### ISSUE THREAD

**Issue by Sekuraz** [sx-aurora-dev/llvm-project#5]
As per above, a build of hpce/release_1.6 fails if ncc is not installed.
I'm working on a fix for that.

**Comment by kaz7** [comment]
Thank you for having an interest.  You may be able to compile it with `-fintegrated-as` option.  We implements llvm-mc and have plans to use it in near future, but we haven't finished that job.

**Comment by Sekuraz** [comment]
where do you want me to put that option? The issue is about the whole clang infrastructure is not building if ncc is not on the machine you build the compiler with. This is actually blocking me from working on this very repository. A fix is compiling right now, I'll link to it once it's ready (approx. 10 minutes)

**Comment by kaz7** [comment]
I misunderstood you were talking about nas related problem.  If not, never mind my suggestion.  Thanks.

**Comment by Sekuraz** [comment]
Please take a look at PR-6 for a suggested fix.

**Comment by simoll** [comment]
@manorom Could you check whether this will work for you?

**Comment by manorom** [comment]
Hi

sorry for not coming to that earlier.

I think the linked patch would break our workflow, by using the Clang in the build directory instead of the (presumptive) install directory for the clang target preset, when building in debug mode.

Our build directory is not persistent (we're using a local SSD which gets cleaned out regularly instead of a slower persistent network storage) and we build and install debug binaries to test them in their install location.
I'm also not entirely convinced that the ncc preset should be available, at all, if ncc is not found at built-time.

But besides these minor nitpicks that looks good to me.

**Comment by simoll** [comment]
> I think the linked patch would break our workflow, by using the Clang in the build directory instead of the (presumptive) install directory for the clang target preset, when building in debug mode.

Ok. That seems fixable. @Sekuraz can you change the patch to work for that use case?

> 
> I'm also not entirely convinced that the ncc preset should be available, at all, if ncc is not found at built-time.

Same here.

> [..]
> But besides these minor nitpicks that looks good to me.

Thanks for having a look!

**Comment by simoll** [comment]
Fixed in `hpce/develop` and `hpce/stable`
